//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct g {

        /// Base translation: 更新
        public static var update : String = NSLocalizedString("g.update", comment: "")

        /// Base translation: 取消
        public static var cancel : String = NSLocalizedString("g.cancel", comment: "")

        /// Base translation: 确定
        public static var ok : String = NSLocalizedString("g.ok", comment: "")

        /// Base translation: 编辑
        public static var edit : String = NSLocalizedString("g.edit", comment: "")

        /// Base translation: 复制
        public static var copy : String = NSLocalizedString("g.copy", comment: "")

        /// Base translation: 下一步
        public static var next : String = NSLocalizedString("g.next", comment: "")

        /// Base translation: 载入中，请稍等
        public static var loading : String = NSLocalizedString("g.loading", comment: "")

        /// Base translation: 确认
        public static var confirm : String = NSLocalizedString("g.confirm", comment: "")

        /// Base translation: 完成
        public static var done : String = NSLocalizedString("g.done", comment: "")

        /// Base translation: 关闭
        public static var close : String = NSLocalizedString("g.close", comment: "")


        public struct error {

            /// Base translation: 服务器拒绝请求
            public static var api_reject : String = NSLocalizedString("g.error.api_reject", comment: "")

            /// Base translation: 是否确认要离开？
            public static var exit : String = NSLocalizedString("g.error.exit", comment: "")

            /// Base translation: 维护中
            public static var app_disabled : String = NSLocalizedString("g.error.app_disabled", comment: "")

            /// Base translation: 当前没有网路
            public static var network_unreachable : String = NSLocalizedString("g.error.network_unreachable", comment: "")

            /// Base translation: 登入 Token 已过时
            public static var token_expired : String = NSLocalizedString("g.error.token_expired", comment: "")

            /// Base translation: 网路发生问题，请再试一次
            public static var network_issue : String = NSLocalizedString("g.error.network_issue", comment: "")

            /// Base translation: 请输入
            public static var emptyform : String = NSLocalizedString("g.error.emptyform", comment: "")

            /// Base translation: 版本过时
            public static var invalid_version : String = NSLocalizedString("g.error.invalid_version", comment: "")

            /// Base translation: 连线已逾时，请重新尝试
            public static var network_timeout : String = NSLocalizedString("g.error.network_timeout", comment: "")

            /// Base translation: 检查到无效的 Token
            public static var token_invalid : String = NSLocalizedString("g.error.token_invalid", comment: "")

            /// Base translation: 广播失败
            public static var broadcast_fail : String = NSLocalizedString("g.error.broadcast_fail", comment: "")

            /// Base translation: App 目前正在维护
            public static var app_disabled_detail : String = NSLocalizedString("g.error.app_disabled_detail", comment: "")

            /// Base translation: 查无资料
            public static var empty_data : String = NSLocalizedString("g.error.empty_data", comment: "")

        }
    }

    public struct str_validate {


        public struct error {

            /// Base translation: 助记词格式错误，必须包含 12 个以上单词
            public static var mnemonic_12_words_at_least : String = NSLocalizedString("str_validate.error.mnemonic_12_words_at_least", comment: "")

            /// Base translation: 两次密码输入不同
            public static var confirm_pwd_diff_with_pwd : String = NSLocalizedString("str_validate.error.confirm_pwd_diff_with_pwd", comment: "")

            /// Base translation: 助记词格式错误，侦测到非英文字元的单词 %@，请确认是否正确输入，并且使用一个半形空白分开各个单词
            public static func mnemonic_invalid_character(_ value1 : String) -> String {
                return String(format: NSLocalizedString("str_validate.error.mnemonic_invalid_character", comment: ""), value1)
            }

            /// Base translation: %@长度需为 %@-%@ 字元
            public static func common_length_invalid(_ value1 : String, _ value2 : String, _ value3 : String) -> String {
                return String(format: NSLocalizedString("str_validate.error.common_length_invalid", comment: ""), value1, value2, value3)
            }

            /// Base translation: %@首尾不得空白
            public static func common_space_prefix_or_suffix(_ value1 : String) -> String {
                return String(format: NSLocalizedString("str_validate.error.common_space_prefix_or_suffix", comment: ""), value1)
            }

            /// Base translation: 助记词格式错误，侦测到含有非小写的单词 %@
            public static func mnemonic_contain_uppercase(_ value1 : String) -> String {
                return String(format: NSLocalizedString("str_validate.error.mnemonic_contain_uppercase", comment: ""), value1)
            }

            /// Base translation: %@只允许使用英数字
            public static func common_allow_alphanumeric_only(_ value1 : String) -> String {
                return String(format: NSLocalizedString("str_validate.error.common_allow_alphanumeric_only", comment: ""), value1)
            }

        }

        public struct field {

            /// Base translation: 助记词
            public static var mnemonic : String = NSLocalizedString("str_validate.field.mnemonic", comment: "")

            /// Base translation: 钱包名称
            public static var wallet_name : String = NSLocalizedString("str_validate.field.wallet_name", comment: "")

            /// Base translation: 确认密码
            public static var confirm_pwd : String = NSLocalizedString("str_validate.field.confirm_pwd", comment: "")

            /// Base translation: 名称
            public static var identity_name : String = NSLocalizedString("str_validate.field.identity_name", comment: "")

            /// Base translation: 密码
            public static var pwd : String = NSLocalizedString("str_validate.field.pwd", comment: "")

        }
    }

    public struct tab {

        /// Base translation: 交易
        public static var trade : String = NSLocalizedString("tab.trade", comment: "")

        /// Base translation: 钱包
        public static var wallet : String = NSLocalizedString("tab.wallet", comment: "")

        /// Base translation: 我的
        public static var mine : String = NSLocalizedString("tab.mine", comment: "")

    }
}
