# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

username "webmaster@git4u.net"
app_identifier "com.gib.OfflineWallet"
price_tier 0
languages(['zh-Hans', 'zh-Hant'])
submission_information({    
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})

# skip_binary_upload true
automatic_release false
app_rating_config_path  './fastlane/metadata/itunes_rating_config.json'
app_icon './fastlane/metadata/AppIcon.png'
ipa './build/Hope Seed_AppStore.ipa'